title: My comsci website
author: Daniel Poon
email: dpoon1@ocdsb.ca
description: This is my awsome website it's full of info. 

# social links
twitter_username: N/A
github_username:  daniep1

show_excerpts: true # set to false to remove excerpts on the homepage

Theme: minima 
